spring:
  application.name: sc-shipping-service # for config server and service-registry
  cloud.stream.bindings:
    shipOrder-in-0.destination:
    shipOrder-out-0.destination:
eureka.instance:
  non-secure-port: 8080
  secure-port-enabled: false
shipping.duration: 0
